global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'complif-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:3000']
        labels:
          service: 'complif-rule-engine'
